### ISSUE TITLE
How to fix DNS Internal Resolution inside the Nginx docker container

### ISSUE THREAD

**Issue by seanly** [seanly/appset#8]
测试方案：通过docker-compose.yml启动2个服务，一个nginx，演示异常现象

1. 准备环境，后启动第一次

file: docker-compose.yml

```yaml

version: '3'

services:
  hello1:
    image: hashicorp/http-echo
    container_name: hello1
    networks:
      - intranet
    command: -listen=:8081 -text="hello world1"
  hello2:
    image: hashicorp/http-echo:latest
    container_name: hello2
    networks:
      - intranet

    command: -listen=:8082 -text="hello world2"

  tengine:
    image: seanly/appset:tengine-2.4.1
    ports:
      - "8080:8080"
    volumes:
      - ./conf/vhosts:/usr/local/nginx/conf/vhosts:rw
    networks:
      - intranet

networks:
  intranet:

```

file: ./conf/vhosts/hello.conf

```nginx
server {

    # resolver 127.0.0.11 ipv6=off valid=10s;

    server_name 127.0.0.1;
    listen 8080;
    # 增加默认变量, 避免NGINX检测变量未设置而导致启动失败
    set $u_uri '';
    set $app_name '';

    location / {
        proxy_pass http://hello1:8081;
    }
}

```

```

docker-compose up -d 
docker-compose exec tengine bash
curl 127.0.0.1:8080
```

输出结果：

![image](https://github.com/seanly/appset/assets/232069/4c002f15-3fa8-4ab6-89c3-b881f2953827)

2. 修改 hello1 服务的内容为 'hello world1-2'，如下图的方式启动。

![image](https://github.com/seanly/appset/assets/232069/01b18e27-e14a-4245-bed5-45736a28e8f9)

上图的异常原因主要是因为 nginx 的 dns 缓存导致。

3. 处理方式

将下面的配置添加到 nginx 配置中，这里的 127.0.0.11 是 docker 内部的 dns 解析地址。或者手动执行 `nginx -s reload`

```
resolver 127.0.0.11 ipv6=off valid=10s;
```

![image](https://github.com/seanly/appset/assets/232069/ce988324-0438-4c4b-87ab-3c8472323149)
